version: 2.1

orbs:

  python: circleci/python@2.0.3
  coveralls: coveralls/coveralls@2.1.1

jobs:

  build_and_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            pytest -v --cov=stickit --cov-report=term-missing
      - coveralls/upload

workflows:
  test_stickit:
    jobs:
      - build_and_test
